name: Monkeytype Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      # MUST be exactly 'v4' with NO extra spaces
      - uses: actions/checkout@v4

      - name: Update Monkeytype Stats
        # MUST be exactly 'main' with NO extra spaces
        uses: monkeytype-hub/monkeytype-readme@main 
        with:
          MONKEYTYPE_API_KEY: ${{ secrets.MONKEYTYPE_API_KEY }}
          mode: 'time' 
          mode_value: '30' 
          theme: 'dark'
